---
- hosts: all
  become: true
  tasks:

  - name: install updates (sudo apt update)
    package:
      update_cache: yes

  - name: install node
    shell: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs


- hosts: all
  tasks:
  - name: Extract app files
    unarchive:
      src: app/*.zip
      dest: ~/weight-tracker/
    
#   - name: copy environment file
#     copy: 
#       src: app/.
#       dest: ~/weight-tracker/

  - name: copy script to run node
    tags: run_node
    copy:
      src: run_node.sh
      dest:  ~/weight-tracker/run_node.sh
      mode: u+x

  - name: Create an entry like "@reboot run_dode.sh"
    tags: cron
    cron:
      name: "run node reboot"
      special_time: reboot
      job: "~/weight-tracker/run_node.sh"


- hosts: 10.0.0.7
  tasks:

  - name: init db (only one machine)
    command: npm run initdb
    tags: initdb
    args:
      chdir: ~/weight-tracker/


- hosts: all
  become: true
  tasks:
  - name: reboot all machines with updated env file
    reboot:
