---
- hosts: all
  become: true
  tasks:

  - name: install updates (sudo apt update)
    package:
      update_cache: yes

  - name: install unzip
    package:
      name: unzip

  - name: install node
    shell: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs


- hosts: all
  tasks:

  - name: Delete app directory
    file:
      state: absent
      path: ~/weight-tracker  
          
  - name: Create app directory
    file:
      path:  ~/weight-tracker/
      state: directory
      mode: '0755'
    
  - name: Extract app files
    unarchive:
      src: app/{{ build_id }}.zip
      dest: ~/weight-tracker/
    
#   - name: install node mon #if you buld on pc it won't work without it
#     shell: |
#       cd ~/weight-tracker/; npm install --save-dev nodemon@2

  - name: copy script to run node
    tags: run_node
    copy:
      src: run_node.sh
      dest:  ~/weight-tracker/run_node.sh
      mode: u+x

  - name: Create an entry like "@reboot run_dode.sh"
    tags: cron
    cron:
      name: "run node reboot"
      special_time: reboot
      job: "~/weight-tracker/run_node.sh"


- hosts: "{{ init_host_ip }}"
  tasks:

  - name: init db (only one machine)
    command: npm run initdb
    tags: initdb
    args:
      chdir: ~/weight-tracker/


- hosts: all
  become: true
  tasks:
  - name: reboot all machines with updated env file
    reboot:
